on:
  workflow_dispatch:
  pull_request:

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AI PR Review
        run: echo "AI reviewing PR..."

  build:
    needs: ai-review
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building app..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying app..."
  
  Notficaiton: 
    needs: deploy
    runs-on: ubuntu-latest
    steps:
       - name: Notify Slack
             curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Pipeline completed"}' \
            ${{ secrets.SLACK_WEBHOOK }}

